// <auto-generated />
namespace JoeAbpMpa.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Asset_Entity_add : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Asset_Entity_add));
        
        string IMigrationMetadata.Id
        {
            get { return "201801290044134_Asset_Entity_add"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
